name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: {{RUNS_ON}}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Lint with ruff
        run: ruff check src/
        
      - name: Check formatting
        run: black --check src/
        
      - name: Type check
        run: mypy src/{{PACKAGE_NAME}}
        continue-on-error: true
        
      - name: Run tests
        run: pytest --cov=src/{{PACKAGE_NAME}} --cov-report=xml
